version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - reconai-node_modules:/app/node_modules
      - reconai-pnpm-store:/app/.pnpm-store
      # Only mount extensions directory
      - vscode-extensions:/home/node/.vscode-server/extensions
    environment:
      - PNPM_HOME=/app/.pnpm-store
      - DATABASE_URL=postgres://postgres:postgres@db:5432/recon_ai
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 10
    user: node
    tty: true
    stdin_open: true

  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recon_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  reconai-node_modules:
  reconai-pnpm-store:
  vscode-extensions:
