version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    command: pnpm dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/recon_ai
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recon_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
