FROM node:lts-alpine3.22

# System setup (as root)
RUN apk add --no-cache git openssh-client bash

# Enable pnpm
RUN corepack enable && \
    corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy lockfile first for better caching
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy rest of the code
COPY . .

# Ensure permissions are correct
RUN chown -R node:node /app

USER node

# Expose and start
EXPOSE 3000
